### ISSUE TITLE
Support to query browser versions

### ISSUE THREAD

**Issue by toomuchdesign** [levithomason/canibrowse#10]
Hi @levithomason,
I was thinking about how to feed this library with a `browserlist` query string or directly with `browserlist`output.

The main problem to me seems that 'browserlist' considers a smaller set of browsers than 'bowser', leaving a grey area between the 2 libraries.

What do you think about it?
Greetings! 😃

**Comment by levithomason** [comment]
I'm definitely in favor.  Per the readme:

![image](https://user-images.githubusercontent.com/5067638/31344570-e9559708-acc7-11e7-9f99-a4238c7f9455.png)


😄 

That said, I've commented on an open issue over at bowser to support browserlist names.  In the meantime, we can just make a map that normalizes the two sets of names.  A PR would be awesome.

**Comment by toomuchdesign** [comment]
I'd like to understand how we might deal with the fact that `caniuse-lite` (used by browserlist) seems to considers only a [limited set of browsers](https://github.com/ben-eb/caniuse-lite/blob/master/data/browsers.js).

Let's say we supply `last 2 versions` querystring: we would be able make a version check only for those browser [supported by`caniuse-lite`](https://github.com/ben-eb/caniuse-lite/blob/master/data/browsers.js).

Any other minor browser (eg. [Vivaldi](https://vivaldi.com)), would not be part of the `browserlist`list and therefore we would be forced to process it as an unknown/unrecognized browser.

**Comment by levithomason** [comment]
If I understand the issue correctly, I think we'd just note in the docs that using browser queries may limit the number of recognized browsers.

Users can opt to [just get detection info](https://github.com/levithomason/canibrowse#just-get-detection-info) and do edge case checks themselves.

**Comment by levithomason** [comment]
@toomuchdesign closing for housekeeping, happy to reopen if we find a path forward and time to execute it.
